baseURL = 'https://docs.elliebot.net/'
languageCode = 'en-us'
title = 'The documentation site for EllieBot'

[markup]
  [markup.tableOfContents]
    # Some relatively important headers, like cc triggers, are on level 4;
    # we want to have those in our table of contents, so we need to set this to 4.
    endLevel = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Enable HTML tags in Markdown
      unsafe = true

[module]
  [[module.imports]]
  path = 'github.com/McShelby/hugo-theme-relearn'

[outputs]
  home = [ "html", "search", "searchpage" ]

[params]
  themeVariant = [
    { identifier = "zen-auto", name = "Zen Light/Dark", auto = [ "zen-light", "zen-dark" ] },
    { identifier = "zen-light" },
    { identifier = "zen-dark"  },
  ]

  collapsibleMenu = true
  disableRootBreadcrumb = true
  disableInlineCopyToClipboard = true
  editURL = 'https://toastielab.dev/EllieBotDevs/EllieBot-docs/src/branch/main/content/'