# Project information
site_name: Elliebot Docs
site_url: https://docs.emotionchild.com
site_description: >-
  The documentation for Ellie.
  Here you can find documentation for Ellie and the Ellie bot systems
site_author: EmotionChild

# Repository
repo_name: EmotionChild/Ellie-v4
repo_url: https://github.com/EmotionChild/Ellie-v4
edit_uri: https://github.com/EmotionChild/EllieBot-Documentation/blob/main/docs

# Copyright
copyright: Copyright &copy; 2020 - 2021 EmotionChild

# Configuration
extra:
  homepage: https://elliebot.emotionchild.com

theme:
  static_templates:
    - 404.html
  features:
    - navigation.instant
    - navigation.tabs
  palette:
          - media: "(prefers-color-scheme: light)"
            scheme: default
            primary: blue
            accent: light blue
            toggle:
                icon: material/weather-sunny
                name: Switch to dark mode
          - media: "(prefers-color-scheme: dark)"
            scheme: slate
            primary: indigo
            accent: light blue
            toggle:
                icon: material/weather-night
                name: Switch to light mode
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/favicon.png
  favicon: assets/favicon.png
nav:
  - Home: index.md
  - Ellie v3:
      - Custom Reactions: v3/custom-reactions.md
      - Placeholders: v3/placeholders.md
      - Permissions System: v3/permissions-system.md
  - Ellie v4:
      - Contribution Steps: contributing.md
      - Installation: v4/installation.md
      - Privacy: v4/privacy_policy.md
  - Giveaway Child:
      - Commands: Giveaway-Child/Commands.md
  - Ticket Child:
      - Commands: Ticket-Child/Commands.md
      - Privacy: Ticket-Child/Privacy.md
  - Musical Child:
      - Coming Soon: coming_soon.md
  - Credits:
      - Credits: credits.md
markdown_extensions:
    - attr_list
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.betterem:
        smart_enable: all
    - admonition
    - meta
    - footnotes
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
    - git-revision-date-localized:
        type: date
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/SVQVzJq
      name: Ellie's Home

