# Project information
site_name: Elliebot Docs
site_url: https://docs.elliebot.net
site_description: >-
  The documentation for Ellie.
  Here you can find documentation for Ellie and the Ellie bot systems
site_author: EmotionChild

# Repository
repo_name: EllieBotDevs/Ellie-bot
repo_url: https://github.com/EllieBotDevs/Ellie-bot
edit_uri: https://github.com/EllieBotDevs/EllieBot-Docs/blob/main/docs

# Copyright
copyright: Copyright &copy; 2018 - 2022 EllieBotDevs

# Configuration
extra:
  homepage: https://www.elliebot.net

theme:
  name: material
  custom_dir: docs/overrides
  static_templates:
    - 404.html
  features:
    - navigation.instant
    - navigation.tabs
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - search.suggest
    - search.highlight
  palette:
          - media: "(prefers-color-scheme: light)"
            scheme: default
            primary: blue
            accent: light blue
            toggle:
                icon: material/weather-sunny
                name: Switch to dark mode
          - media: "(prefers-color-scheme: dark)"
            scheme: slate
            primary: indigo
            accent: light blue
            toggle:
                icon: material/weather-night
                name: Switch to light mode
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/favicon.png
  favicon: assets/favicon.png

nav:
  - Home: index.md
  - Ellie v4:
      - Custom Reactions: v4/custom-reactions.md
      - Placeholders: v4/placeholders.md
      - Permissions System: v4/permissions-system.md
  - Ellie v5:
      - Contribution Steps: contributing.md
      - Installation: v5/coming_soon.md
  - Giveaway Child:
      - Commands: Giveaway-Child/Commands.md
  - SupportChild:
      - Commands: SupportChild/Commands.md
  - Other Stuff:
      - Timestamps: other-things/timestamps.md
  - Credits:
      - Credits: credits.md

markdown_extensions:
    - attr_list
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.betterem:
        smart_enable: all
    - admonition
    - meta
    - footnotes
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - tags
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - git-revision-date-localized:
        type: date
        enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/SVQVzJq
      name: Ellie's Home
    - icon: fontawesome/brands/github
      link: https://github.com/EmotionChild
      name: EmotionChild's GitHub
    - icon: fontawesome/brands/github
      link: https://github.com/EllieBotDevs
      name: EllieBotDevs' Github
  analytics:
    provider: google
    property: UA-181153828-6
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
