repo_url: https://github.com/EmotionChild/EmotionBot-v3
repo_name: EmotionChild/EmotionBot-v3
site_name: EmotionBot Docs
site_url: https://emotionbot.emotionchild.com
site_author: EmotionChild
edit_uri: ""
copyright: Copyright &copy; 2020 - 2021 EmotionChild

theme:
  static_templates:
    - 404.html
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    scheme: slate
    primary: black
    accent: light blue
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/favicon.png
  favicon: assets/favicon.png
nav:
  - Home: index.md
markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  - admonition
  - meta
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
